[package]
name = "hygiene-test"
version = "0.1.0"
authors = ["leo60228 <leo@60228.dev>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.7"
proc-macro2 = "1.0.24"
